name: snowflake-performance-optimizer
channels:
  - snowflake
  - conda-forge
  - nodefaults
dependencies:
  - python=3.9
  - streamlit=1.35.0
  - snowflake-snowpark-python=1.18.0
  - pandas=2.2.2
  - snowflake-connector-python=3.10.1

